"""Initial migration

Revision ID: 69ebb1f27825
Revises: 
Create Date: 2025-11-23 00:43:54.005380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69ebb1f27825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('overdue', 'due_soon', 'scheduled', 'in_progress', 'completed', 'cancelled', name='maintenancestatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='maintenancepriority'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_mileage', sa.Integer(), nullable=False),
    sa.Column('due_mileage', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('assigned_technician', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parts_needed', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_items_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_items_vehicle_id'))

    op.drop_table('maintenance_items')
    
    # Drop enums
    sa.Enum(name='maintenancestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='maintenancepriority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
