[control]
control ansible_host=3.220.167.254 ansible_user=ubuntu ansible_ssh_private_key_file=/home/shemal/.ssh/Fleet_Manager_Key_Pair.pem 

[workers]
worker1 ansible_host=44.197.212.179 ansible_user=ubuntu ansible_ssh_private_key_file=/home/shemal/.ssh/Fleet_Manager_Key_Pair.pem 

worker2 ansible_host=54.89.217.149 ansible_user=ubuntu ansible_ssh_private_key_file=/home/shemal/.ssh/Fleet_Manager_Key_Pair.pem 


[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
